#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config layout bsp
yabai -m config window_gap 0
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config smart_borders on
yabai -m config window_animation_duration 0.0
yabai -m config external_bar all:32:0
yabai -m signal --add event=space_changed action="sketchybar --trigger space_change"

echo "yabai loaded"

